#!/usr/bin/env zsh

# Credit for this file: https://github.com/aaronbieber/dotfiles

# Color constants
yellow="\e[33;40m"
red="\e[31;40m"
green="\e[32;40m"
reset="\e[39;49m"

# Who am I?
me=`basename $0`

# Get options.
LNOPTS=""
if [ $# -gt 0 ]; then
  if [[ "$1" == "-f" ]]; then
    LNOPTS="-f"
  else
    echo "Unrecognized option: $1"
    cat << EOF
Usage: $me [OPTIONS]

    Options:
    -f    Force 'ln' to create a new link, even if one already exists with the
          same name.
EOF
    exit 1
  fi
fi

# Install and configure zsh, oh my zsh and vim plugins
if [ ! -d "$ZSH" ]; then
  echo "Installing and configuring oh my zsh"
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sed 's:env zsh -l::g')"
  echo "Installing zsh autosuggestions and syntax highlighting"
  git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
  git clone https://github.com/zsh-users/zsh-syntax-highlighting ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
  git clone https://github.com/bhilburn/powerlevel9k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel9k
  rm "$HOME/.zshrc"
fi

# This appears to be the "best" way to get the canonicalized path to where this
# script is located, which is, presumably, where all of my dotfiles are.
# Lifted from http://stackoverflow.com/a/4774063
pushd `dirname $0` > /dev/null
SCRIPTPATH=`pwd`
BINPATH="$SCRIPTPATH/bin"
SCRIPTPATH="$SCRIPTPATH/configs"
popd > /dev/null

pushd ~ > /dev/null

echo "Creating symlinks for all configuration files in $SCRIPTPATH."
echo ""

ln -s $LNOPTS "$SCRIPTPATH/config/nvim" ".config/nvim" > /dev/null 2>&1

for dotfile in `find $SCRIPTPATH -mindepth 1 -maxdepth 1`; do
  if [[ "${dotfile##*/}" == "bashrc" ]]; then
    linkfile=".bash_profile"
  else
    linkfile=".${dotfile##*/}"
  fi

  if [ -d "./$linkfile" ]

  if [ -e "$linkfile" ]; then
    echo -n "${yellow}Exists${reset}"
  else
    ln -s $LNOPTS "$dotfile" "./$linkfile" > /dev/null 2>&1

    if [ $? -eq 0 ]; then
      echo -n "${green}OK${reset}    "
    else
      echo -n "${red}Failed${reset}"
    fi
  fi
  echo " $dotfile -> $linkfile... "
done

if [ ! -f "$HOME/.config/nvim/autoload/plug.vim" ]; then
  echo "Installing vim-plug and the plugins"
  curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  nvim +PlugInstall +qall
fi

if [ ! "$ZSH" ]; then
  env zsh -l
fi
