export ZSH="$HOME/.oh-my-zsh"

source "$HOME/.zsh_functions"

t

[[ "$TMUX" == "" ]] && TERM=xterm-256color

ZSH_THEME=""
DEFAULT_USER=`whoami`

HIST_STAMPS="mm/dd/yyyy"
DISABLE_UPDATE_PROMPT=true
DISABLE_AUTO_TITLE="true"
DISABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"

plugins=(
    git
    colorize
    themes
    zsh-autosuggestions
    zsh-syntax-highlighting
)

if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

vew_on_path=$(type virtualenvwrapper >/dev/null; echo $?)
if [[ "$vew_on_path" -eq 0 || -x "$(command -v virtualenvwrapper.sh)" ]]; then
  export VIRTUALENVWRAPPER_PYTHON=$(which python3)
  source virtualenvwrapper.sh
  export WORKON_HOME="$HOME/.virtualenvs"
  if [[ ! -d $WORKON_HOME ]]; then
    mkdir $WORKON_HOME
  fi
  plugins=($plugins virtualenvwrapper)
fi

setopt autolist
setopt cdablevars
setopt autonamedirs
setopt histignoredups
setopt listtypes
setopt nolistbeep

source $ZSH/oh-my-zsh.sh

fpath+=$ZSH_CUSTOM/themes/pure

autoload -U promptinit; promptinit
prompt pure

bindkey -v
bindkey '^R' history-incremental-search-backward

autoload -Uz add-zsh-hook
add-zsh-hook precmd set-title-precmd
add-zsh-hook preexec set-title-preexec

alias pip='pip3'
alias python='python3'
alias vim='nvim'
alias ta='tmux attach'
alias tad='tmux attach -d'
alias tl='tmux ls'
alias urldecode='python3 -c "import sys, urllib.parse as ul; print(ul.unquote_plus(sys.argv[1]))"'
alias ssh='TERM=xterm-256color ssh -A'

if [[ `uname` == "Darwin" ]]; then
    alias l="ls -lhFG"
    alias la="ls -lhFGA"
    alias ltr="ls -lhFGtr"
    alias lsr="ls -lhFGSr"
else
    alias l="ls -lhF --group-directories-first --color=always"
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_COMMAND='fd --type f --color=never'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_ALT_C_COMMAND='fd --type d . --color=never'
export FZF_DEFAULT_OPTS='--height 75% --multi --reverse --bind ctrl-f:page-down,ctrl-b:page-up'
export FZF_CTRL_T_OPTS="--preview 'bat --color=always --line-range :500 {}'"
export FZF_ALT_C_OPTS="--preview 'tree -C {} | head -100'"
