export ZSH="$HOME/.oh-my-zsh"

source "$HOME/.zsh_functions"

ZSH_THEME="powerlevel9k/powerlevel9k"
DEFAULT_USER=`whoami`
POWERLEVEL9K_MODE="nerdfont-complete"
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_RPROMPT_ON_NEWLINE=true
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
POWERLEVEL9K_SHORTEN_DIR_LENGTH=4
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_beginning"
POWERLEVEL9K_PYTHON_ICON='\uf81f'
POWERLEVEL9K_VIRTUALENV_FOREGROUND='black'
POWERLEVEL9K_VIRTUALENV_BACKGROUND='green'
POWERLEVEL9K_TIME_ICON='\uf017'
POWERLEVEL9K_TIME_FORMAT="%D{%H:%M}"
POWERLEVEL9K_STATUS_VERBOSE=false
POWERLEVEL9K_VCS_CLEAN_FOREGROUND='black'
POWERLEVEL9K_VCS_CLEAN_BACKGROUND='green'
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='black'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='yellow'
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='black'
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='yellow'
POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND='black'
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='blue'
POWERLEVEL9K_STATUS_OK_IN_NON_VERBOSE=true
POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=0
POWERLEVEL9K_CUSTOM_INTERNET_SIGNAL="zsh_internet_signal"
POWERLEVEL9K_CUSTOM_INTERNET_SIGNAL_BACKGROUND="black"
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="%F{blue}\u256D\u2500%f"
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%F{blue}\u2570\uf460%f "
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context os_icon virtualenv ssh root_indicator dir dir_writable vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(command_execution_time status background_jobs time disk_usage ram custom_internet_signal battery)
HIST_STAMPS="mm/dd/yyyy"
DISABLE_UPDATE_PROMPT=true

DISABLE_AUTO_TITLE="true"

DISABLE_CORRECTION="true"

COMPLETION_WAITING_DOTS="true"

DISABLE_UNTRACKED_FILES_DIRTY="true"

plugins=(
    git
    colorize
    themes
    zsh-autosuggestions
    zsh-syntax-highlighting
    virtualenv
)

if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python3
vnw_script="/usr/local/bin/virtualenvwrapper.sh"
if [[ -e "$vnw_script" ]]; then
    source "$vnw_script"
fi

vew_on_path=$(type virtualenvwrapper >/dev/null; echo $?)
if [[ "$vew_on_path" -eq 0 || -e "$vnw_script" ]]; then
  if [[ ! -d "$HOME/.virtualenvs" ]]; then
    mkdir "$HOME/.virtualenvs"
  fi
  export WORKON_HOME="$HOME/.virtualenvs"
  plugins=($plugins virtualenvwrapper)
fi

setopt autolist
setopt cdablevars
setopt autonamedirs
setopt histignoredups
setopt listtypes
setopt nolistbeep

source $ZSH/oh-my-zsh.sh

bindkey '^R' history-incremental-search-backward

autoload -Uz add-zsh-hook
add-zsh-hook precmd set-title-precmd
add-zsh-hook preexec set-title-preexec

alias pip='pip3'
alias python='python3'
alias vim='nvim'
alias ta='tmux attach'
alias tl='tmux ls'
alias urldecode='python3 -c "import sys, urllib.parse as ul; print(ul.unquote_plus(sys.argv[1]))"'
alias ssh='TERM=xterm-256color ssh -A'
alias plus='python3 manage.py shell_plus'

alias l="ls -lhFG"
alias la="ls -lhFGA"
alias ltr="ls -lhFGtr"
alias lsr="ls -lhFGSr"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_COMMAND="rg --files"

export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export PYTHONPATH="senpai:fashioni:$PYTHONPATH"
export COMPOSE_FILE=local.yml
