export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="powerlevel9k/powerlevel9k"
DEFAULT_USER=`whoami`
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator background_jobs virtualenv time)
POWERLEVEL9K_MODE="nerdfont-complete"
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_from_right"
POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
POWERLEVEL9K_SHORTEN_DELIMITER=""
POWERLEVEL9K_VCS_CLEAN_BACKGROUND="green"
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND="yellow"
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND="red"
POWERLEVEL9K_HIDE_BRANCH_ICON="true"

DISABLE_AUTO_TITLE="true"

DISABLE_CORRECTION="true"

COMPLETION_WAITING_DOTS="true"

DISABLE_UNTRACKED_FILES_DIRTY="true"

plugins=(
    git
    colorize
    themes
    zsh-autosuggestions
    zsh-syntax-highlighting
    virtualenv
)

if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python3
vnw_script="/usr/local/bin/virtualenvwrapper.sh"
if [[ -e "$vnw_script" ]]; then
    source "$vnw_script"
fi

vew_on_path=$(type virtualenvwrapper >/dev/null; echo $?)
if [[ "$vew_on_path" -eq 0 || -e "$vnw_script" ]]; then
  if [[ ! -d "$HOME/.virtualenvs" ]]; then
    mkdir "$HOME/.virtualenvs"
  fi
  export WORKON_HOME="$HOME/.virtualenvs"
  plugins=($plugins virtualenvwrapper)
fi

setopt autolist
setopt cdablevars
setopt autonamedirs
setopt histignoredups
setopt listtypes
setopt nolistbeep

source $ZSH/oh-my-zsh.sh

bindkey '^R' history-incremental-search-backward

function nicediff {
  diff -W `tput cols` -y "$@" | colordiff | less
}

alias pip='pip3'
alias python='python3'
alias vim='nvim'
alias ta='tmux attach'
alias tl='tmux ls'
alias urldecode='python -c "import sys, urllib as ul; print ul.unquote_plus(sys.argv[1])"'
alias ssh='ssh -A'
alias plus='python3 manage.py shell_plus'

function top() {
  if [ $# -eq 0 ]; then
    /usr/bin/top -o cpu
  else
    /usr/bin/top "$@"
  fi
}

alias l="ls -lhFG"
alias la="ls -lhFGA"
alias ltr="ls -lhFGtr"
alias lsr="ls -lhFGSr"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export COMPOSE_FILE=local.yml
export DJANGO_READ_DOT_ENV_FILE=true
