require("nvim-treesitter.configs").setup({
  ensure_installed = {
    "bash",
    "c",
    "cmake",
    "cpp",
    "fish",
    "go",
    "graphql",
    "html",
    "java",
    "javascript",
    "json",
    "json5",
    "kotlin",
    "latex",
    "lua",
    "make",
    "markdown",
    "prisma",
    "python",
    "rust",
    "scss",
    "solidity",
    "toml",
    "typescript",
    "vim",
    "vue",
    "yaml",
  },
  sync_install = false,
  highlight = {
    enable = true,
    additional_vim_regex_highlighting = true,
  },
  indent = { enable = true, disable = { "python" } },
  rainbow = {
    enable = true,
    extended_mode = true,
    max_file_lines = nil,
    colors = {
      "#ffd700",
      "#da70d6",
      "#87cefa",
    },
    termcolors = {
      "Yellow",
      "Magenta",
      "Blue",
    },
  },
})
